import scrollSmoother from './helpers/scrollSmoother';
import aside from './components/aside';
import canvas from './components/canvas';
import slider from './components/certificate';
import cursor from './components/cursor';
import hero from './components/hero';
import linesGrid from './components/lines-grid';
import yearBlock from './components/year-block';
import documentReady from './helpers/documentReady';
// import preloader from './helpers/preloader';
import viewHeight from './helpers/viewHeight';
import lazyImages from './modules/lazyImages';
import skills from './components/skills';
import showAnimation from './components/showAnimation';
import contact from './components/contact';
import social from './components/social';
import projects from './components/projects';

documentReady(() => {
	// console.log('Document is ready');
	viewHeight();
	// preloader();
	lazyImages();
	canvas();
	hero();
	linesGrid();
	yearBlock();
	scrollSmoother();
	cursor();
	aside();
	slider();
	skills();
	showAnimation();
	contact();
	social();
	projects();
});
